name: wearable_app
description: Resgate SOS for Wear OS (Smartwatches)
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  wear: ^1.1.0
  sos_kernel:
    path: ../../packages/sos_kernel
  sos_ui:
    path: ../../packages/sos_ui
  sos_transports:
    path: ../../packages/sos_transports

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
