name: desktop_station
publish_to: none
version: 15.0.0+1
environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  sos_kernel:
    path: ../../packages/sos_kernel
  sos_ui:
    path: ../../packages/sos_ui
  sos_transports:
    path: ../../packages/sos_transports
  intl: any
  path_provider: ^2.1.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

