name: sos_vault
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  drift: ^2.12.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  crypto: ^3.0.3
  sodium_libs: ^2.0.0
dev_dependencies:
  drift_dev: ^2.12.0
  build_runner: ^2.4.6
