name: sos_transports
description: SOS Multi-Protocol Transport Layer
version: 1.0.0
environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  flutter_blue_plus: ^2.1.1
  bonsoir: ^6.0.1
  permission_handler: ^12.0.1
  mqtt_client: ^10.0.0
  win_ble: ^1.1.1
  flutter_ble_peripheral: ^2.1.0
  bluez: ^0.8.0
  nearby_connections: ^4.3.0
  wifi_iot: ^0.3.18
  lan_scanner: ^4.0.0
  udp: ^5.0.0
  dart_ping: ^9.0.1
  network_info_plus: ^7.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  serial_port_win32: any
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
