name: mobile_app
version: 15.0.0+1
publish_to: none
environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  sos_kernel:
    path: ../../packages/sos_kernel
  sos_ui:
    path: ../../packages/sos_ui
  sos_transports:
    path: ../../packages/sos_transports
  sos_calls:
    path: ../../packages/sos_calls
  flutter_webrtc: ^1.3.0
  intl: any
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
